//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookDetail> BookDetails { get; set; }
        public virtual DbSet<RegisterUser> RegisterUsers { get; set; }
    
        public virtual int spCreateBookDetails(string bookName, string author, string rating)
        {
            var bookNameParameter = bookName != null ?
                new ObjectParameter("BookName", bookName) :
                new ObjectParameter("BookName", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("Author", author) :
                new ObjectParameter("Author", typeof(string));
    
            var ratingParameter = rating != null ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateBookDetails", bookNameParameter, authorParameter, ratingParameter);
        }
    
        public virtual int spDeleteBookDetails(Nullable<int> bkid)
        {
            var bkidParameter = bkid.HasValue ?
                new ObjectParameter("bkid", bkid) :
                new ObjectParameter("bkid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteBookDetails", bkidParameter);
        }
    
        public virtual int spDeleteRegisterUsers(Nullable<int> id, string name, string surname, string email, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteRegisterUsers", idParameter, nameParameter, surnameParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<spGetBookDetials_Result> spGetBookDetials(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetBookDetials_Result>("spGetBookDetials", idParameter);
        }
    
        public virtual int spRegiterUsers(string name, string surname, string email, string password)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spRegiterUsers", nameParameter, surnameParameter, emailParameter, passwordParameter);
        }
    
        public virtual int spUpdateBookDetials(Nullable<int> bkid, string bookName, string author, string rating)
        {
            var bkidParameter = bkid.HasValue ?
                new ObjectParameter("bkid", bkid) :
                new ObjectParameter("bkid", typeof(int));
    
            var bookNameParameter = bookName != null ?
                new ObjectParameter("BookName", bookName) :
                new ObjectParameter("BookName", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("Author", author) :
                new ObjectParameter("Author", typeof(string));
    
            var ratingParameter = rating != null ?
                new ObjectParameter("Rating", rating) :
                new ObjectParameter("Rating", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateBookDetials", bkidParameter, bookNameParameter, authorParameter, ratingParameter);
        }
    
        public virtual int spUpdateRegisterUsers(Nullable<int> id, string name, string surname, string email, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var surnameParameter = surname != null ?
                new ObjectParameter("Surname", surname) :
                new ObjectParameter("Surname", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateRegisterUsers", idParameter, nameParameter, surnameParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<spViewAllBookDetials_Result> spViewAllBookDetials()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewAllBookDetials_Result>("spViewAllBookDetials");
        }
    
        public virtual ObjectResult<spViewAllRegisterUsers_Result> spViewAllRegisterUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spViewAllRegisterUsers_Result>("spViewAllRegisterUsers");
        }
    }
}
